# Generated by Django 4.2.7 on 2024-02-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.CharField(default=True, max_length=200)),
                ('preciounitario', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cantidad', models.DecimalField(decimal_places=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=0, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.CharField(default=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Comercializadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=0, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Jefe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hola', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productoName', models.CharField(max_length=200)),
                ('productoDescription', models.CharField(blank=True, max_length=500)),
                ('productoPrice', models.DecimalField(decimal_places=0, default=True, max_digits=10)),
                ('productoImage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('productoCantidad', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoPopular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productoName', models.CharField(max_length=200)),
                ('productoImagen', models.CharField(default=True, max_length=10000)),
                ('productoPrice', models.DecimalField(decimal_places=0, default=True, max_digits=10)),
            ],
        ),
    ]
