# Generated by Django 4.2.7 on 2024-02-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mundo',
        ),
        migrations.AddField(
            model_name='producto',
            name='productoCategoria',
            field=models.ManyToManyField(to='api.categorias'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='productoImage',
            field=models.CharField(default=True, max_length=10000),
        ),
    ]
