# Generated by Django 4.2.7 on 2024-02-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_productoimagen_productopopular_productoimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productopopular',
            old_name='productoImage',
            new_name='productoImagen',
        ),
        migrations.RemoveField(
            model_name='productopopular',
            name='productoCantidad',
        ),
        migrations.RemoveField(
            model_name='productopopular',
            name='productoCategoria',
        ),
        migrations.RemoveField(
            model_name='productopopular',
            name='productoDescription',
        ),
    ]
