# Generated by Django 4.2.7 on 2024-02-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_productoimage_productopopular_productoimagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='productoImage',
            field=models.ImageField(upload_to='productos/'),
        ),
    ]
