# Generated by Django 4.2.7 on 2024-02-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_producto_productoimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('preciounitario', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cantidad', models.DecimalField(decimal_places=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=0, editable=False, max_digits=10)),
            ],
        ),
    ]
